### ISSUE TITLE
Failed to resolve entry for package "@antv/graphin" with Graphin 2.7.10 and Vite

### ISSUE THREAD

**Issue by eakl** [antvis/Graphin#441]
### Describe the bug

Vite + Graphin **2.7.9** works as expected

Vite + Graphin **2.7.10** throw an error

```javascript
❯ pnpm dev

> graphin@0.0.0 dev /Users/eakl/dev/graphin
> vite

Port 5173 is in use, trying another one...

  VITE v3.1.1  ready in 324 ms

  ➜  Local:   http://localhost:5174/
  ➜  Network: use --host to expose
✘ [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "@antv/graphin". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/.pnpm/esbuild@0.15.7/node_modules/esbuild/lib/main.js:933:27:
      933 │               let result = await callback2({
          ╵                            ^

    at packageEntryFailure (file:///Users/eakl/dev/graphin/node_modules/.pnpm/vite@3.1.1/node_modules/vite/dist/node/chunks/dep-a713b95d.js:34823:11)
    at resolvePackageEntry (file:///Users/eakl/dev/graphin/node_modules/.pnpm/vite@3.1.1/node_modules/vite/dist/node/chunks/dep-a713b95d.js:34820:5)
    at tryNodeResolve (file:///Users/eakl/dev/graphin/node_modules/.pnpm/vite@3.1.1/node_modules/vite/dist/node/chunks/dep-a713b95d.js:34570:20)
    at Context.resolveId (file:///Users/eakl/dev/graphin/node_modules/.pnpm/vite@3.1.1/node_modules/vite/dist/node/chunks/dep-a713b95d.js:34343:28)
    at Object.resolveId (file:///Users/eakl/dev/graphin/node_modules/.pnpm/vite@3.1.1/node_modules/vite/dist/node/chunks/dep-a713b95d.js:41016:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (file:///Users/eakl/dev/graphin/node_modules/.pnpm/vite@3.1.1/node_modules/vite/dist/node/chunks/dep-a713b95d.js:41240:26)
    at async file:///Users/eakl/dev/graphin/node_modules/.pnpm/vite@3.1.1/node_modules/vite/dist/node/chunks/dep-a713b95d.js:41411:34
    at async callback (/Users/eakl/dev/graphin/node_modules/.pnpm/esbuild@0.15.7/node_modules/esbuild/lib/main.js:933:28)
    at async handleRequest (/Users/eakl/dev/graphin/node_modules/.pnpm/esbuild@0.15.7/node_modules/esbuild/lib/main.js:713:30)

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/esbuild@0.15.7/node_modules/esbuild/lib/main.js:855:22:
      855 │         let promise = setup({
          ╵                       ^

    at setup (file:///Users/eakl/dev/graphin/node_modules/.pnpm/vite@3.1.1/node_modules/vite/dist/node/chunks/dep-a713b95d.js:41401:19)
    at handlePlugins (/Users/eakl/dev/graphin/node_modules/.pnpm/esbuild@0.15.7/node_modules/esbuild/lib/main.js:855:23)
    at Object.buildOrServe (/Users/eakl/dev/graphin/node_modules/.pnpm/esbuild@0.15.7/node_modules/esbuild/lib/main.js:1149:7)
    at /Users/eakl/dev/graphin/node_modules/.pnpm/esbuild@0.15.7/node_modules/esbuild/lib/main.js:2117:17
    at new Promise (<anonymous>)
    at Object.build (/Users/eakl/dev/graphin/node_modules/.pnpm/esbuild@0.15.7/node_modules/esbuild/lib/main.js:2116:14)
    at build (/Users/eakl/dev/graphin/node_modules/.pnpm/esbuild@0.15.7/node_modules/esbuild/lib/main.js:1963:51)
    at file:///Users/eakl/dev/graphin/node_modules/.pnpm/vite@3.1.1/node_modules/vite/dist/node/chunks/dep-a713b95d.js:41188:46
    at Array.map (<anonymous>)

  The plugin "vite:dep-scan" was triggered by this import

    src/Graphin.tsx:1:20:
      1 │ import Graphin from '@antv/graphin'
        ╵                     ~~~~~~~~~~~~~~~

Build failed with 1 error:
node_modules/.pnpm/esbuild@0.15.7/node_modules/esbuild/lib/main.js:933:27: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "@antv/graphin". The package may have incorrect main/module/exports specified in its package.json.
```

### Your Example Website or App

https://stackblitz.com/

### Steps to Reproduce the Bug or Issue

1. run `pnpm create vite graphin --template react-ts`
2. Add graphin version 2.7.10
3. Import Graphin in a component
4. run `pnpm run dev`

You will experience the same error

### Expected behavior

Graphin 2.7.10 should work with vite

### Platform

- OS: macOS
- Browser: All

**Comment by xiaoyuer14** [comment]
vite config

defineConfig add resolve alias

`
  resolve: {
    alias: [
      {
        find: "@antv/graphin",
        replacement: "@antv/graphin/lib/index.js"
      }
    ]
  }
`
